version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    command: python -m flask run --host=0.0.0.0